### ISSUE TITLE
caching system for printer status

### ISSUE THREAD

**Issue by mrjones-plip** [synshop/discord_faqbot#18]
right now we on demand query every printer for their status. this can be slow and prone to a DoS attack.  Instead, we should have the printers be polled every N minutes and cache this result.  We may also opt to use MQTT subscriptions if this is easier/less resource intensive.

this ticket is likely a good candidate to refactor the code using [this more robust python API](https://mchrisgm.github.io/bambulabs_api/) instead of our DIY one.

**Comment by mrjones-plip** [comment]
when we implement this feature, we should work around the scenario when one printer is offline, no printer status can be reached.  Instead we should denote the printer was unreachable (and possibly show the last time it was seen)

This looks like this:

```
2024-12-30 15:52:31 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/mrjones/Documents/discord_faqbot/venv/lib/python3.13/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/home/mrjones/Documents/discord_faqbot/main.py", line 85, in on_message
    await message.channel.send(get_printer_status())
                               ~~~~~~~~~~~~~~~~~~^^
  File "/home/mrjones/Documents/discord_faqbot/main.py", line 28, in get_printer_status
    msg = subscribe.simple(topics=printer["topic_name"],hostname=printer["ip"],port=printer["port"],auth=auth,tls=tls)
  File "/home/mrjones/Documents/discord_faqbot/venv/lib/python3.13/site-packages/paho/mqtt/subscribe.py", line 277, in simple
    callback(_on_message_simple, topics, qos, userdata, hostname, port,
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             client_id, keepalive, will, auth, tls, protocol, transport,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             clean_session, proxy_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrjones/Documents/discord_faqbot/venv/lib/python3.13/site-packages/paho/mqtt/subscribe.py", line 182, in callback
    client.connect(hostname, port, keepalive)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrjones/Documents/discord_faqbot/venv/lib/python3.13/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
           ~~~~~~~~~~~~~~^^
  File "/home/mrjones/Documents/discord_faqbot/venv/lib/python3.13/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
                 ~~~~~~~~~~~~~~~~~~~^^
  File "/home/mrjones/Documents/discord_faqbot/venv/lib/python3.13/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/home/mrjones/Documents/discord_faqbot/venv/lib/python3.13/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.13/lib/python3.13/socket.py", line 840, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.13/lib/python3.13/socket.py", line 975, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by mrjones-plip** [comment]
fixed in #24
